pipeline {
  agent any 
  stages {
    stage('Deploy') { 
      steps {
        sh '''
          ssh sifiso@localhost
          cd ~/node-server
          git pull
          yarn
          yarn restart
          exit
        '''
      }
    }
  }
}
